{
    'name': 'Card Management',
    'version': '1.0',
    'summary': 'Card Management Software',
    'sequence': -100,
    'description': """Card Management Software""",
    'category': 'Productivity',
    'website': 'https://www.odoo.com',
    'license': 'LGPL-3',
    'depends': ['report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        'views/info.xml',
        'views/department.xml',
        'views/description.xml',
        'views/sql_view_report.xml',
        'reports/report.xml',
        'reports/info_card.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
